[project]
name = "ytbox"
version = "1.0.0"
description = "A friendly yt-dlp wrapper."
requires-python = ">=3.10"
dependencies = [
    "yt-dlp",
    "rich",
    "packaging",
]

[project.scripts]
ytbox = "ytbox.main:cli_entry"

[tool.setuptools.packages.find]
where = ["."]


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
