name: Build standalones

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact: ytbox-windows
          - os: ubuntu-latest
            artifact: ytbox-linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -e . pyinstaller

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onedir --name ytbox --hidden-import yt_dlp.extractor --collect-submodules yt_dlp ytbox/main.py
        shell: pwsh

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          pyinstaller \
            --onedir \
            --name ytbox \
            --hidden-import yt_dlp.extractor \
            --collect-submodules yt_dlp \
            ytbox/main.py

      - name: Add README (Windows)
        if: runner.os == 'Windows'
        run: Copy-Item ./standalone-readmes/WINDOWS_README.md dist\ytbox\README.md
        shell: pwsh

      - name: Add README (Linux)
        if: runner.os == 'Linux'
        run: cp ./standalone-readmes/LINUX_README.md dist/ytbox/README.md

      - name: Zip artifact (Windows)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path dist\ytbox\* -DestinationPath ytbox-windows.zip
        shell: pwsh

      - name: Zip artifact (Linux)
        if: runner.os == 'Linux'
        run: |
          cd dist
          zip -r ../ytbox-linux.zip ytbox/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}-package
          path: ${{ matrix.artifact }}.zip

  release:
  needs: build
  runs-on: ubuntu-latest
  if: startsWith(github.ref, 'refs/tags/')

  steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: ytbox-windows-package
        path: windows-download

    - name: Prepare Windows release asset
      run: mv windows-download/ytbox-windows.zip ytbox-windows.zip

    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: ytbox-linux-package
        path: linux-download

    - name: Prepare Linux release asset
      run: mv linux-download/ytbox-linux.zip ytbox-linux.zip

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ytbox-windows.zip,ytbox-linux.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
